[project]
name = "rvwr"
version = "0.1.0"
description = "Customizable LLM-based PR Reviewer that understands your repo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygithub>=2.6.1",
    "unidiff>=0.7.5",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
